name: client
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: '^5.4.0'
  socket_io_client: 2.0.3+1
  openapi_generator_annotations: ^5.0.2
  image_picker: ^1.0.7
  music_server_api:
    path: ./api/music_server_api
  web_socket_channel: ^2.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  built_collection: ^5.1.1
  flutter_localized_locales: ^2.0.5

dev_dependencies:
  openapi_generator: ^5.0.2
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
